// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimesheetManagement.Infrastructure.Persistence;

#nullable disable

namespace TimesheetManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TimesheetDbContext))]
    [Migration("20260821111150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.ApprovalHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ActionBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("TimesheetWeekId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActionBy");

                    b.HasIndex("TimesheetWeekId");

                    b.ToTable("ApprovalHistories");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Code = "INT-001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Internal tooling and platform work.",
                            IsActive = true,
                            Name = "Internal Tools"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            Code = "CWR-100",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "External client website redesign.",
                            IsActive = true,
                            Name = "Client Website Revamp"
                        });
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000001"),
                            Classification = "OpEx",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Keep-the-lights-on maintenance work.",
                            IsActive = true,
                            IsBillable = false,
                            Name = "Platform Maintenance",
                            ProjectId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000002"),
                            Classification = "CapEx",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "New capability build-out.",
                            IsActive = true,
                            IsBillable = false,
                            Name = "New Feature Development",
                            ProjectId = new Guid("aaaaaaaa-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000003"),
                            Classification = "CapEx",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Client-facing design work.",
                            IsActive = true,
                            IsBillable = true,
                            Name = "Design & UX",
                            ProjectId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-0000-0000-0000-000000000004"),
                            Classification = "OpEx",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ongoing client support and change requests.",
                            IsActive = true,
                            IsBillable = true,
                            Name = "Client Support",
                            ProjectId = new Guid("aaaaaaaa-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.TimesheetEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FriHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MonHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SatHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SunHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ThuHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("TimesheetWeekId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TueHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("WedHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectTaskId");

                    b.HasIndex("TimesheetWeekId", "ProjectId", "ProjectTaskId")
                        .IsUnique();

                    b.ToTable("TimesheetEntries");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.TimesheetWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalHours")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("WeekEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("UserId", "WeekStartDate")
                        .IsUnique();

                    b.ToTable("TimesheetWeeks");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalAuthId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalAuthId")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@timesheet.local",
                            ExternalAuthId = "11111111-1111-1111-1111-111111111111",
                            FullName = "Ava Admin",
                            IsActive = true,
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manager@timesheet.local",
                            ExternalAuthId = "22222222-2222-2222-2222-222222222222",
                            FullName = "Mia Manager",
                            IsActive = true,
                            Role = "Manager"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "employee@timesheet.local",
                            ExternalAuthId = "33333333-3333-3333-3333-333333333333",
                            FullName = "Eli Employee",
                            IsActive = true,
                            ManagerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.ApprovalHistory", b =>
                {
                    b.HasOne("TimesheetManagement.Domain.Entities.User", "ActionByUser")
                        .WithMany()
                        .HasForeignKey("ActionBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimesheetManagement.Domain.Entities.TimesheetWeek", "TimesheetWeek")
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("TimesheetWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionByUser");

                    b.Navigation("TimesheetWeek");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.Project", b =>
                {
                    b.HasOne("TimesheetManagement.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.ProjectTask", b =>
                {
                    b.HasOne("TimesheetManagement.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.TimesheetEntry", b =>
                {
                    b.HasOne("TimesheetManagement.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimesheetManagement.Domain.Entities.ProjectTask", "ProjectTask")
                        .WithMany()
                        .HasForeignKey("ProjectTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TimesheetManagement.Domain.Entities.TimesheetWeek", "TimesheetWeek")
                        .WithMany("Entries")
                        .HasForeignKey("TimesheetWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ProjectTask");

                    b.Navigation("TimesheetWeek");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.TimesheetWeek", b =>
                {
                    b.HasOne("TimesheetManagement.Domain.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TimesheetManagement.Domain.Entities.User", "User")
                        .WithMany("TimesheetWeeks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.User", b =>
                {
                    b.HasOne("TimesheetManagement.Domain.Entities.User", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.TimesheetWeek", b =>
                {
                    b.Navigation("ApprovalHistories");

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("TimesheetManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("TimesheetWeeks");
                });
#pragma warning restore 612, 618
        }
    }
}
